In [1]:
import numpy as np
import sys

In [2]:
a =np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a[0]

1

In [5]:
b = np.array([i for i in range(6)])
b

array([0, 1, 2, 3, 4, 5])

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [8]:
b.shape

(6,)

In [9]:
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('int32')

In [12]:
c8 = np.array([1,2,3], dtype='uint8')
c16 = np.array([1,2,3], dtype='uint16')
c32 = np.array([1,2,3], dtype='uint32')

In [19]:
print(c8.dtype)
print(c8.shape)
print(c8.ndim)
print(c8.itemsize)
print(c8.size)
print(c8.nbytes)

uint8
(3,)
1
1
3
3


In [20]:
print(c16.dtype)
print(c16.shape)
print(c16.ndim)
print(c16.itemsize)
print(c16.size)
print(c16.nbytes)

uint16
(3,)
1
2
3
6


In [21]:
print(c32.dtype)
print(c32.shape)
print(c32.ndim)
print(c32.itemsize)
print(c32.size)
print(c32.nbytes)

uint32
(3,)
1
4
3
12


In [26]:
arr2d = np.array([[i for i in range(7)], [i for i in range(8, 15)]])
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
arr2d[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [30]:
arr2d[:,2]

array([ 2, 10])

In [31]:
arr2d[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [32]:
np.zeros(4)

array([0., 0., 0., 0.])

In [40]:
np.zeros((4,2,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.full(8, 44)

array([44, 44, 44, 44, 44, 44, 44, 44])

In [38]:
np.full((8,3), 44)

array([[44, 44, 44],
       [44, 44, 44],
       [44, 44, 44],
       [44, 44, 44],
       [44, 44, 44],
       [44, 44, 44],
       [44, 44, 44],
       [44, 44, 44]])

In [46]:
np.full_like(a, 33)

array([33, 33, 33])

In [47]:
np.full(a, 33)

array([[[33, 33, 33],
        [33, 33, 33]]])

In [44]:
a

array([1, 2, 3])

In [45]:
a.shape

(3,)

In [49]:
np.random.rand(4,2)

array([[0.73472992, 0.35050097],
       [0.88299918, 0.83699576],
       [0.78507944, 0.39345584],
       [0.73437052, 0.18619799]])

In [52]:
np.random.randint(4,7, size=(4,2))

array([[5, 5],
       [5, 4],
       [6, 4],
       [6, 5]])

In [53]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
a

array([1, 2, 3])

In [56]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [60]:
np.repeat([a], 4, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [64]:
p = np.ones((5,5))
p

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
p[1:4,1:4] = 0
p

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
p[2,2] = 9
p

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
a

array([1, 2, 3])

In [68]:
a-2


array([-1,  0,  1])

In [69]:
a** 2


array([1, 4, 9])

In [76]:
p.reshape(25)

array([1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 9., 0., 1., 1., 0.,
       0., 0., 1., 1., 1., 1., 1., 1.])

In [75]:
r = np.ones((4,4))
r

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
r.reshape(8,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [78]:
r.reshape(2,8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [80]:
r.reshape(16)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
r.reshape(1,16)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [86]:
data = np.genfromtxt('data.txt', delimiter=',')
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [89]:
data.astype('uint16')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=uint16)

In [90]:
    data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [91]:
a

array([1, 2, 3])

In [92]:
a>1

array([False,  True,  True])

In [93]:
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [113]:
row=0
col=0
arr = np.zeros((6,5), dtype="uint8")
for i in range(1, 31):
    arr[row][col] = i
    col+= 1
    if i % 5 == 0:
        col = 0
        row += 1

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [116]:
arr[2:4, :2]


array([[11, 12],
       [16, 17]], dtype=uint8)

In [118]:
arr[:4]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=uint8)

In [119]:
arr[:4, 1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]], dtype=uint8)

In [120]:
arr[0,1]

2

In [122]:
arr[1,2]

8

In [123]:
arr[2,3]

14

In [124]:
arr[3,4]

20

In [135]:
arr[[0,1,2,3],0]

array([ 1,  6, 11, 16], dtype=uint8)

In [136]:
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20], dtype=uint8)

In [137]:
arr[[:4],[1,2,3,4]]

SyntaxError: invalid syntax (2383533446.py, line 1)

In [138]:
arr[[0,4,5]]

array([[ 1,  2,  3,  4,  5],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]], dtype=uint8)

In [147]:
arr[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=uint8)