In [22]:
import numpy as np

In [23]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.twos(4)

AttributeError: module 'numpy' has no attribute 'twos'

In [7]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [8]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
np.linspace(1, 10, 6        )

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [18]:
np.linspace(2, 10, 6)

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [11]:
4.6-2.8

1.7999999999999998

In [12]:
6.4-4.6

1.8000000000000007

In [17]:
1.8*5

9.0

In [14]:
10/6

1.6666666666666667

In [19]:
8/5

1.6

In [22]:
z = np.zeros(4)
z

array([0., 0., 0., 0.])

In [25]:
z.shape

(4,)

In [31]:
z.shape = (6,)
z

ValueError: cannot reshape array of size 4 into shape (6,)

In [43]:
z = np.array([4, 3])
z

array([4, 3])

In [44]:
z.shape

(2,)

In [39]:
z[1]

3

In [1]:
import numpy as np

In [2]:
a =np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b = np.array([[1,2,3,4,5], [11,22,33,44,55]])
b

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [7]:
b[1,2:]

array([33, 44, 55])

In [9]:
b[:,2]

array([ 3, 33])

In [12]:
b[:,2:16:2]

array([[ 3,  5],
       [33, 55]])

In [13]:
b[:,2:16:3]

array([[ 3],
       [33]])

In [19]:
np.full((2,3), ((2,4,6), (1,3,1)))

array([[2, 4, 6],
       [1, 3, 1]])

In [20]:
np.full((2,3), (33))

array([[33, 33, 33],
       [33, 33, 33]])

In [24]:
np.full((2,3), 33)

array([[33, 33, 33],
       [33, 33, 33]])

In [26]:
a = np.array([[1,2,3]])
a

array([[1, 2, 3]])

In [27]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [28]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [29]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [30]:
np.repeat(a, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
np.repeat(a, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [32]:
np.repeat(b, 3, axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [38]:
pattern = np.ones((5,5))
pattern

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
pattern[1:4,1:4]=0
pattern

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
pattern[2,2]=9
pattern

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
pattern = np.ones((5,5))
pattern

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
a = np.array([1,'dddf', 2, 'erer', True])
a

array(['1', 'dddf', '2', 'erer', 'True'], dtype='<U11')

In [46]:
np.sort(a)

array(['1', '2', 'True', 'dddf', 'erer'], dtype='<U11')

In [49]:
a = np.array([1,2,3,2,3,4,5,3,2,1])
a

array([1, 2, 3, 2, 3, 4, 5, 3, 2, 1])

In [50]:
a > 3

array([False, False, False, False, False,  True,  True, False, False,
       False])

In [52]:
a[a==3]

array([3, 3, 3])

In [58]:
idx = np.where(a==3)
print(idx)
print(idx[0])
print(idx[0][2])

(array([2, 4, 7], dtype=int64),)
[2 4 7]
7


In [59]:
a %2 == 0

array([False,  True, False,  True, False,  True, False, False,  True,
       False])

In [60]:
a[a %2 == 0]

array([2, 2, 4, 2])

In [61]:
np.where(a %2 == 0)

(array([1, 3, 5, 8], dtype=int64),)